// Copyright Epic Games, Inc. All Rights Reserved.
// This file is automatically generated. Changes to this file may be overwritten.

using System.Runtime.InteropServices;

namespace EOS_SDK.Logging
{

	[StructLayout(LayoutKind.Sequential, Pack = 8)]
    public struct LogMessage
	{
		public IntPtr Category;
        public IntPtr Message;
        public LogLevel Level;
	}
}